const en = {
  tagline: 'Find jobs, housing, services, and community updates in one place.',
  nav: {
    categories: 'Categories',
    search: 'Search',
    publish: 'Post',
    dashboard: 'My Posts',
    business: 'Business',
    myAccount: 'Account',
    login: 'Sign In',
  },
  common: {
    loading: 'Loading',
    empty: 'No items yet',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    apply: 'Apply',
    reset: 'Reset',
    name: 'Name',
    email: 'Email',
    price: 'Price',
    city: 'City',
    region: 'Region',
    status: 'Status',
    views: 'Views',
    publishedAt: 'Published',
    contact: 'Contact',
  },
  home: {
    heroTitle: 'Liberia Chinese Classifieds & Community',
    heroSubtitle: 'Trusted listings, local services, and business opportunities.',
    searchPlaceholder: 'Search keyword, category, or location',
    popularCategories: 'Popular Categories',
    latestPosts: 'Latest Posts',
    featuredPosts: 'Featured Listings',
    publishCTA: 'Post Now',
    bannerTitle: 'Business Spotlight · Premium Slots',
  },
  search: {
    title: 'Search & Filters',
    keyword: 'Keyword',
    category: 'Category',
    city: 'City',
    region: 'Region',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    sort: 'Sort By',
    latest: 'Latest',
    priceLow: 'Price: Low to High',
    priceHigh: 'Price: High to Low',
  },
  post: {
    top: 'Top',
    featured: 'Featured',
    urgent: 'Urgent',
    report: 'Report',
    favorite: 'Save',
    share: 'Share',
    contactWechat: 'WeChat',
    contactWhatsapp: 'WhatsApp',
    contactPhone: 'Phone',
  },
  publish: {
    title: 'Publish a Post',
    stepDetails: 'Listing Details',
    stepContact: 'Contact Info',
    stepReview: 'Review',
    hint: 'All posts are reviewed before they go live.',
  },
  auth: {
    hint: 'Sign in with email to publish and manage listings.',
  },
  dashboard: {
    title: 'My Listings',
    myPosts: 'Your Posts',
    statusActive: 'Active',
    statusPending: 'Pending',
    statusExpired: 'Expired',
    bump: 'Refresh',
  },
  admin: {
    title: 'Admin Console',
    moderation: 'Moderation',
    pricing: 'Pricing',
    banners: 'Banners',
  },
  footer: {
    description: 'A classifieds and community portal for the Liberia Chinese community.',
    rules: 'Rules',
    privacy: 'Privacy',
    contact: 'Contact',
    address: 'Monrovia, Liberia',
  },
};

export default en;
