export const en = {
  // Navigation
  nav: {
    home: 'Home',
    about: 'About',
    events: 'Events',
    news: 'News',
    directory: 'Directory',
    resources: 'Resources',
    gallery: 'Gallery',
    contact: 'Contact',
    donate: 'Donate',
    membership: 'Membership',
    dashboard: 'Dashboard',
    logout: 'Logout',
    login: 'Login',
    join: 'Join',
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    category: 'Category',
    language: 'Language',
    english: 'English',
    chinese: ' 中文',
    readMore: 'Read More',
    learnMore: 'Learn More',
    viewDetails: 'View Details',
    register: 'Register',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    download: 'Download',
    share: 'Share',
    featured: 'Featured',
    new: 'New',
    updated: 'Updated',
  },

  // Home
  home: {
    title: 'Welcome to Liberian Chinese Society',
    subtitle: 'Building community, promoting culture, fostering business connections',
    hero_cta: 'Join Us Today',
    hero_donate: 'Support Our Mission',
    mission_title: 'Our Mission',
    mission_description: 'To promote Chinese culture, support community members, facilitate business networking, and strengthen bonds between the Liberian and Chinese communities.',
    latest_news: 'Latest News',
    upcoming_events: 'Upcoming Events',
    view_all_events: 'View All Events',
    partners: 'Our Partners',
  },

  // About
  about: {
    title: 'About Liberian Chinese Society',
    mission: 'Mission',
    history: 'History',
    committee: 'Leadership Committee',
    bylaws: 'Constitution & Bylaws',
    constitution_pdf: 'Download Constitution',
    bylaws_pdf: 'Download Bylaws',
  },

  // Events
  events: {
    title: 'Events',
    upcoming: 'Upcoming Events',
    past: 'Past Events',
    all_events: 'All Events',
    no_events: 'No events found',
    event_details: 'Event Details',
    date: 'Date',
    time: 'Time',
    location: 'Location',
    register: 'RSVP',
    registered: 'You are registered',
    cancel_rsvp: 'Cancel RSVP',
    add_to_calendar: 'Add to Calendar',
    attendees: 'Attendees',
    available_seats: 'Available Seats',
    sold_out: 'Sold Out',
    free_event: 'Free Event',
    ticket_price: 'Ticket Price',
    buy_tickets: 'Buy Tickets',
    event_type: 'Event Type',
    description: 'Description',
  },

  // News
  news: {
    title: 'News & Announcements',
    all_posts: 'All Posts',
    no_posts: 'No posts found',
    published: 'Published',
    by: 'By',
    read_full_article: 'Read Full Article',
    share_article: 'Share Article',
    related_posts: 'Related Posts',
  },

  // Directory
  directory: {
    title: 'Business Directory',
    search_placeholder: 'Search businesses or members',
    filter_by_category: 'Filter by Category',
    no_listings: 'No listings found',
    contact: 'Contact',
    website: 'Visit Website',
    call: 'Call',
    wechat: 'WeChat',
    email_contact: 'Email',
    submit_listing: 'Submit Your Listing',
    featured_listings: 'Featured Listings',
    all_listings: 'All Listings',
    business_type: 'Business Type',
    phone: 'Phone',
    address: 'Address',
    hours: 'Hours',
  },

  // Resources
  resources: {
    title: 'Resources',
    newcomer_guides: 'Newcomer Guides',
    legal_information: 'Legal & Visa Information',
    local_services: 'Local Services',
    emergency_contacts: 'Emergency Contacts',
    useful_links: 'Useful Links',
    no_resources: 'No resources found',
    view_resource: 'View Resource',
    download_resource: 'Download',
  },

  // Gallery
  gallery: {
    title: 'Gallery',
    photos: 'Photos',
    videos: 'Videos',
    events_gallery: 'Event Photos',
    community_gallery: 'Community Gallery',
    no_items: 'No gallery items found',
  },

  // Contact
  contact: {
    title: 'Contact Us',
    get_in_touch: 'Get in Touch',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    hours: 'Office Hours',
    social_media: 'Follow Us',
    wechat_official: 'WeChat Official Account',
    whatsapp: 'WhatsApp',
    message_placeholder: 'Your message...',
    send_message: 'Send Message',
    thank_you: 'Thank you for your message!',
    map: 'Location Map',
  },

  // Donate
  donate: {
    title: 'Support Our Mission',
    donate_now: 'Donate Now',
    one_time: 'One-time Donation',
    monthly: 'Monthly Donation',
    custom_amount: 'Custom Amount',
    donation_amounts: 'Quick Amounts',
    your_donation_helps: 'Your donation helps us continue our work',
    tax_deductible: 'Tax-deductible donation',
    sponsorship: 'Sponsorship Opportunities',
    sponsor_benefits: 'Sponsor Benefits',
    gold_tier: 'Gold Sponsor',
    silver_tier: 'Silver Sponsor',
    bronze_tier: 'Bronze Sponsor',
  },

  // Membership
  membership: {
    title: 'Join Our Community',
    benefits: 'Member Benefits',
    tiers: 'Membership Tiers',
    free_tier: 'Free Member',
    standard_tier: 'Standard Member',
    premium_tier: 'Premium Member',
    patron_tier: 'Patron Member',
    annual_fee: 'Annual Fee',
    join_now: 'Join Now',
    already_member: 'Already a member?',
    sign_in: 'Sign In',
    member_benefits_1: 'Access to exclusive events',
    member_benefits_2: 'Community networking opportunities',
    member_benefits_3: 'Newsletter and announcements',
    member_benefits_4: 'Member directory listing',
    member_benefits_5: 'Special discounts',
  },

  // Footer
  footer: {
    about_us: 'About Us',
    quick_links: 'Quick Links',
    follow_us: 'Follow Us',
    newsletter: 'Newsletter',
    subscribe: 'Subscribe',
    email_placeholder: 'Your email',
    privacy_policy: 'Privacy Policy',
    terms_of_service: 'Terms of Service',
    code_of_conduct: 'Code of Conduct',
    contact_us: 'Contact Us',
    copyright: '© 2025 Liberian Chinese Society. All rights reserved.',
  },

  // Auth
  auth: {
    login: 'Login',
    signup: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    confirm_password: 'Confirm Password',
    forgot_password: 'Forgot Password?',
    reset_password: 'Reset Password',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    magic_link_sent: 'Check your email for a login link',
    send_magic_link: 'Send Magic Link',
    continue_with_google: 'Continue with Google',
    logout: 'Logout',
    session_expired: 'Your session has expired. Please login again.',
  },

  // Dashboard
  dashboard: {
    title: 'Member Dashboard',
    welcome: 'Welcome',
    my_profile: 'My Profile',
    membership_status: 'Membership Status',
    rsvp_history: 'RSVP History',
    invoices: 'Invoices & Receipts',
    edit_profile: 'Edit Profile',
    upgrade_membership: 'Upgrade Membership',
    no_rsvps: 'No RSVPs yet',
    no_invoices: 'No invoices',
    member_since: 'Member Since',
    status_active: 'Active',
    status_expired: 'Expired',
    status_pending: 'Pending',
  },

  // Admin
  admin: {
    title: 'Admin Dashboard',
    overview: 'Overview',
    manage_events: 'Manage Events',
    manage_posts: 'Manage Posts',
    manage_directory: 'Manage Directory',
    manage_users: 'Manage Users',
    manage_sponsors: 'Manage Sponsors',
    manage_galleries: 'Manage Galleries',
    analytics: 'Analytics',
    export_members: 'Export Members',
    pending_approvals: 'Pending Approvals',
    total_members: 'Total Members',
    total_events: 'Total Events',
    total_posts: 'Total Posts',
    revenue: 'Revenue',
    create_event: 'Create Event',
    create_post: 'Create Post',
    edit: 'Edit',
    delete: 'Delete',
    approve: 'Approve',
    reject: 'Reject',
    view_details: 'View Details',
    back_to_dashboard: 'Back to Dashboard',
    bulk_actions: 'Bulk Actions',
    select_all: 'Select All',
    delete_selected: 'Delete Selected',
  },

  // Errors
  errors: {
    not_found: 'Page not found',
    unauthorized: 'Unauthorized access',
    server_error: 'Server error occurred',
    network_error: 'Network error',
    validation_error: 'Please check your input',
    something_went_wrong: 'Something went wrong',
    try_again: 'Try again',
    go_home: 'Go Home',
  },

  // Messages
  messages: {
    success_update: 'Updated successfully',
    success_create: 'Created successfully',
    success_delete: 'Deleted successfully',
    confirm_delete: 'Are you sure you want to delete this?',
    confirm_logout: 'Are you sure you want to logout?',
    loading: 'Loading...',
    saving: 'Saving...',
    deleting: 'Deleting...',
  },
};
