const en = {
  tagline: 'Find jobs, housing, services, and community updates in one place.',
  nav: {
    categories: 'Categories',
    search: 'Search',
    publish: 'Post',
    dashboard: 'My Posts',
    business: 'Business',
    myAccount: 'Account',
    login: 'Sign In',
    news: 'Policy News',
  },
  common: {
    loading: 'Loading',
    empty: 'No items yet',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    apply: 'Apply',
    reset: 'Reset',
    name: 'Name',
    email: 'Email',
    price: 'Price',
    city: 'City',
    region: 'Region',
    status: 'Status',
    views: 'Views',
    publishedAt: 'Published',
    contact: 'Contact',
  },
  home: {
    heroTitle: 'Liberia Chinese Classifieds & Community',
    heroSubtitle: 'Trusted listings, local services, and business opportunities.',
    searchPlaceholder: 'Search keyword, category, or location',
    popularCategories: 'Popular Categories',
    latestPosts: 'Latest Posts',
    featuredPosts: 'Featured Listings',
    publishCTA: 'Post Now',
    bannerTitle: 'Business Spotlight · Premium Slots',
  },
  search: {
    title: 'Search & Filters',
    keyword: 'Keyword',
    category: 'Category',
    city: 'City',
    region: 'Region',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    sort: 'Sort By',
    latest: 'Latest',
    priceLow: 'Price: Low to High',
    priceHigh: 'Price: High to Low',
  },
  post: {
    top: 'Top',
    featured: 'Featured',
    urgent: 'Urgent',
    report: 'Report',
    favorite: 'Save',
    share: 'Share',
    contactWechat: 'WeChat',
    contactWhatsapp: 'WhatsApp',
    contactPhone: 'Phone',
  },
  publish: {
    title: 'Publish a Post',
    stepDetails: 'Listing Details',
    stepContact: 'Contact Info',
    stepReview: 'Review',
    hint: 'Posts go live immediately after submission.',
  },
  auth: {
    hint: 'Sign in with phone OTP or email to publish and manage listings.',
    phonePlaceholder: '+231 77 000 0000',
    otpPlaceholder: 'Enter SMS code',
    sendCode: 'Send code',
    verifyCode: 'Verify and continue',
    resend: 'Resend code',
    resendIn: 'Resend ({seconds}s)',
    continueWithGoogle: 'Continue with Google',
    methodPhone: 'Phone OTP',
    methodEmail: 'Email',
    emailPlaceholder: 'Email address',
    sendEmail: 'Send login link',
    emailSent: 'We sent a login link to your email. Click it to finish sign in.',
    missingEnv: 'Supabase env is missing.',
  },
  dashboard: {
    title: 'My Listings',
    myPosts: 'Your Posts',
    statusActive: 'Active',
    statusPending: 'Pending',
    statusExpired: 'Expired',
    bump: 'Refresh',
  },
  admin: {
    title: 'Admin Console',
    moderation: 'Moderation',
    pricing: 'Pricing',
    banners: 'Banners',
    news: 'Policy News',
    posts: 'Posts',
    reports: 'Reports',
    back: 'Back to admin',
  },
  news: {
    title: 'Policy & Official News',
    subtitle: 'Official updates summarized for the Liberia Chinese community.',
    source: 'Source',
    tag: 'Tag',
    date: 'Date',
    filter: 'Filter',
    reset: 'Reset',
    empty: 'No news yet',
    readMore: 'Read original',
    disclaimer: 'AI summary for reference only. Please refer to the original text.',
    whyItMatters: 'Why it matters',
    adminIngest: 'Ingest URL',
    adminSync: 'Sync news',
    adminSyncHint: 'Fetch sources and process the latest 5 items.',
    adminSyncAction: 'Run sync',
    adminEdit: 'Edit news',
    adminQueue: 'Processing queue',
    status: 'Status',
    featured: 'Featured',
    hidden: 'Hidden',
    visible: 'Visible',
    hideAction: 'Hide',
    showAction: 'Show',
    publishAction: 'Publish',
    unpublishAction: 'Unpublish',
    save: 'Save changes',
    reprocess: 'Reprocess',
    useAi: 'Use AI version',
    preview: 'Preview',
    rawExcerpt: 'Raw excerpt',
    overrides: 'Overrides',
    originals: 'Extracted',
  },
  footer: {
    description: 'A classifieds and community portal for the Liberia Chinese community.',
    rules: 'Rules',
    privacy: 'Privacy',
    contact: 'Contact',
    address: 'Monrovia, Liberia',
  },
};

export default en;
