export const zh = {
  // Navigation
  nav: {
    home: '主页',
    about: '关于我们',
    events: '活动',
    news: '新闻',
    directory: '商业目录',
    resources: '资源',
    gallery: '相册',
    contact: '联系我们',
    donate: '捐赠',
    membership: '会员',
    dashboard: '仪表板',
    logout: '退出',
    login: '登录',
    join: '加入',
  },

  // Common
  common: {
    loading: '加载中...',
    error: '发生错误',
    success: '成功',
    close: '关闭',
    back: '返回',
    next: '下一个',
    previous: '上一个',
    search: '搜索',
    filter: '筛选',
    category: '类别',
    language: '语言',
    english: 'English',
    chinese: '中文',
    readMore: '了解更多',
    learnMore: '学习更多',
    viewDetails: '查看详情',
    register: '注册',
    submit: '提交',
    cancel: '取消',
    save: '保存',
    edit: '编辑',
    delete: '删除',
    download: '下载',
    share: '分享',
    featured: '精选',
    new: '新',
    updated: '已更新',
  },

  // Home
  home: {
    title: '利比里亚华人协会欢迎您',
    subtitle: '建设社区，弘扬文化，促进商业联系',
    hero_cta: '立即加入',
    hero_donate: '支持我们的使命',
    mission_title: '我们的使命',
    mission_description: '弘扬中华文化，支持社区成员，促进商业交流，加强利比里亚和中国社区之间的联系。',
    latest_news: '最新新闻',
    upcoming_events: '即将举行的活动',
    view_all_events: '查看所有活动',
    partners: '我们的合作伙伴',
  },

  // About
  about: {
    title: '关于利比里亚华人协会',
    mission: '使命',
    history: '历史',
    committee: '领导委员会',
    bylaws: '章程和细则',
    constitution_pdf: '下载章程',
    bylaws_pdf: '下载细则',
  },

  // Events
  events: {
    title: '活动',
    upcoming: '即将举行的活动',
    past: '过去的活动',
    all_events: '所有活动',
    no_events: '未找到活动',
    event_details: '活动详情',
    date: '日期',
    time: '时间',
    location: '位置',
    register: '报名',
    registered: '您已报名',
    cancel_rsvp: '取消报名',
    add_to_calendar: '添加到日历',
    attendees: '参加者',
    available_seats: '可用座位',
    sold_out: '已售罄',
    free_event: '免费活动',
    ticket_price: '票价',
    buy_tickets: '购买门票',
    event_type: '活动类型',
    description: '描述',
  },

  // News
  news: {
    title: '新闻和公告',
    all_posts: '所有文章',
    no_posts: '未找到文章',
    published: '已发布',
    by: '作者',
    read_full_article: '阅读完整文章',
    share_article: '分享文章',
    related_posts: '相关文章',
  },

  // Directory
  directory: {
    title: '商业目录',
    search_placeholder: '搜索企业或成员',
    filter_by_category: '按类别筛选',
    no_listings: '未找到列表',
    contact: '联系',
    website: '访问网站',
    call: '拨打',
    wechat: '微信',
    email_contact: '电子邮件',
    submit_listing: '提交您的列表',
    featured_listings: '精选列表',
    all_listings: '所有列表',
    business_type: '业务类型',
    phone: '电话',
    address: '地址',
    hours: '营业时间',
  },

  // Resources
  resources: {
    title: '资源',
    newcomer_guides: '新移民指南',
    legal_information: '法律和签证信息',
    local_services: '本地服务',
    emergency_contacts: '紧急联系方式',
    useful_links: '有用链接',
    no_resources: '未找到资源',
    view_resource: '查看资源',
    download_resource: '下载',
  },

  // Gallery
  gallery: {
    title: '相册',
    photos: '照片',
    videos: '视频',
    events_gallery: '活动照片',
    community_gallery: '社区相册',
    no_items: '未找到相册项目',
  },

  // Contact
  contact: {
    title: '联系我们',
    get_in_touch: '保持联系',
    email: '电子邮件',
    phone: '电话',
    address: '地址',
    hours: '办公时间',
    social_media: '关注我们',
    wechat_official: '微信公众号',
    whatsapp: 'WhatsApp',
    message_placeholder: '您的消息...',
    send_message: '发送消息',
    thank_you: '感谢您的消息！',
    map: '位置地图',
  },

  // Donate
  donate: {
    title: '支持我们的使命',
    donate_now: '立即捐赠',
    one_time: '一次性捐赠',
    monthly: '月度捐赠',
    custom_amount: '自定义金额',
    donation_amounts: '快速金额',
    your_donation_helps: '您的捐赠帮助我们继续我们的工作',
    tax_deductible: '可税收抵扣的捐赠',
    sponsorship: '赞助机会',
    sponsor_benefits: '赞助商权益',
    gold_tier: '黄金赞助商',
    silver_tier: '白银赞助商',
    bronze_tier: '青铜赞助商',
  },

  // Membership
  membership: {
    title: '加入我们的社区',
    benefits: '会员权益',
    tiers: '会员等级',
    free_tier: '免费会员',
    standard_tier: '标准会员',
    premium_tier: '高级会员',
    patron_tier: '赞助人会员',
    annual_fee: '年费',
    join_now: '立即加入',
    already_member: '已经是会员？',
    sign_in: '登录',
    member_benefits_1: '独家活动访问权',
    member_benefits_2: '社区交流机会',
    member_benefits_3: '时事通讯和公告',
    member_benefits_4: '会员目录列表',
    member_benefits_5: '特别折扣',
  },

  // Footer
  footer: {
    about_us: '关于我们',
    quick_links: '快速链接',
    follow_us: '关注我们',
    newsletter: '新闻通讯',
    subscribe: '订阅',
    email_placeholder: '您的邮箱',
    privacy_policy: '隐私政策',
    terms_of_service: '服务条款',
    code_of_conduct: '行为准则',
    contact_us: '联系我们',
    copyright: '© 2025 利比里亚华人协会。版权所有。',
  },

  // Auth
  auth: {
    login: '登录',
    signup: '创建账户',
    email: '电子邮件地址',
    password: '密码',
    confirm_password: '确认密码',
    forgot_password: '忘记密码？',
    reset_password: '重置密码',
    no_account: '没有账户？',
    have_account: '已有账户？',
    sign_in: '登录',
    sign_up: '注册',
    magic_link_sent: '检查您的电子邮件以获取登录链接',
    send_magic_link: '发送魔法链接',
    continue_with_google: '继续使用谷歌',
    logout: '退出登录',
    session_expired: '您的会话已过期。请重新登录。',
  },

  // Dashboard
  dashboard: {
    title: '会员仪表板',
    welcome: '欢迎',
    my_profile: '我的资料',
    membership_status: '会员状态',
    rsvp_history: '报名历史',
    invoices: '发票和收据',
    edit_profile: '编辑资料',
    upgrade_membership: '升级会员',
    no_rsvps: '尚无报名',
    no_invoices: '无发票',
    member_since: '会员自',
    status_active: '活跃',
    status_expired: '已过期',
    status_pending: '待定',
  },

  // Admin
  admin: {
    title: '管理员仪表板',
    overview: '概览',
    manage_events: '管理活动',
    manage_posts: '管理文章',
    manage_directory: '管理目录',
    manage_users: '管理用户',
    manage_sponsors: '管理赞助商',
    manage_galleries: '管理相册',
    analytics: '分析',
    export_members: '导出会员',
    pending_approvals: '待批准',
    total_members: '总会员数',
    total_events: '总活动数',
    total_posts: '总文章数',
    revenue: '收入',
    create_event: '创建活动',
    create_post: '创建文章',
    edit: '编辑',
    delete: '删除',
    approve: '批准',
    reject: '拒绝',
    view_details: '查看详情',
    back_to_dashboard: '返回仪表板',
    bulk_actions: '批量操作',
    select_all: '全选',
    delete_selected: '删除所选',
  },

  // Errors
  errors: {
    not_found: '页面未找到',
    unauthorized: '未授权访问',
    server_error: '服务器错误',
    network_error: '网络错误',
    validation_error: '请检查您的输入',
    something_went_wrong: '出错了',
    try_again: '重试',
    go_home: '返回首页',
  },

  // Messages
  messages: {
    success_update: '更新成功',
    success_create: '创建成功',
    success_delete: '删除成功',
    confirm_delete: '您确定要删除吗？',
    confirm_logout: '您确定要退出登录吗？',
    loading: '加载中...',
    saving: '保存中...',
    deleting: '删除中...',
  },
};

export default zh;
