const zh = {
  tagline: '找工作、找房、找服务，一站搞定',
  nav: {
    categories: '分类',
    search: '搜索',
    publish: '发布信息',
    dashboard: '我的发布',
    business: '商家名录',
    myAccount: '个人中心',
    login: '登录',
  },
  common: {
    loading: '加载中',
    empty: '暂无内容',
    submit: '提交',
    cancel: '取消',
    save: '保存',
    edit: '编辑',
    delete: '删除',
    apply: '应用',
    reset: '重置',
    name: '姓名',
    email: '邮箱',
    price: '价格',
    city: '城市',
    region: '区域',
    status: '状态',
    views: '浏览量',
    publishedAt: '发布时间',
    contact: '联系方式',
  },
  home: {
    heroTitle: '利比里亚华人分类信息平台',
    heroSubtitle: '社区信息、商机、人脉都在这里',
    searchPlaceholder: '搜索关键词、类别或地区',
    popularCategories: '热门分类',
    latestPosts: '最新信息',
    featuredPosts: '精选推荐',
    publishCTA: '马上发布',
    bannerTitle: '商家推广位 · 欢迎合作',
  },
  search: {
    title: '搜索与筛选',
    keyword: '关键词',
    category: '分类',
    city: '城市',
    region: '区域',
    minPrice: '最低价',
    maxPrice: '最高价',
    sort: '排序',
    latest: '最新发布',
    priceLow: '价格从低到高',
    priceHigh: '价格从高到低',
  },
  post: {
    top: '置顶',
    featured: '推荐',
    urgent: '加急',
    report: '举报',
    favorite: '收藏',
    share: '分享',
    contactWechat: '微信',
    contactWhatsapp: 'WhatsApp',
    contactPhone: '电话',
  },
  publish: {
    title: '发布新信息',
    stepDetails: '基本信息',
    stepContact: '联系方式',
    stepReview: '发布确认',
    hint: '提交后将自动发布。',
  },
  auth: {
    hint: '使用手机号验证码或邮箱登录，发布与管理你的信息。',
    phonePlaceholder: '+231 77 000 0000',
    otpPlaceholder: '输入短信验证码',
    sendCode: '发送验证码',
    verifyCode: '验证并登录',
    resend: '重新发送验证码',
    resendIn: '重新发送 ({seconds}s)',
    continueWithGoogle: '使用 Google 继续',
    methodPhone: '手机验证码',
    methodEmail: '邮箱登录',
    emailPlaceholder: '邮箱地址',
    sendEmail: '发送登录链接',
    emailSent: '登录链接已发送到邮箱，请查收并点击完成登录。',
    missingEnv: 'Supabase 环境变量缺失。',
  },
  dashboard: {
    title: '我的发布',
    myPosts: '我的帖子',
    statusActive: '展示中',
    statusPending: '审核中',
    statusExpired: '已过期',
    bump: '刷新置顶',
  },
  admin: {
    title: '管理后台',
    moderation: '内容审核',
    pricing: '推广价格',
    banners: '广告位',
  },
  footer: {
    description: '面向利比里亚华人社区的分类信息与生活服务平台。',
    rules: '平台规则',
    privacy: '隐私政策',
    contact: '联系我们',
    address: '蒙罗维亚 · Liberia',
  },
};

export default zh;
